apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  name: {{ include "wordpress.fullname" . }}-deploy
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress.labels" . | nindent 8 }}
    spec:
      volumes:
      - name: wp-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName | default ( include "wordpress.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.name | required "images is not found!" }}:{{ .Values.image.tag }}
        name: {{ .Release.Name }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
        env:
          {{- toYaml .Values.env | nindent 8 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe }}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}

