apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  name: {{ include "wordpress.fullname" . }}-svc
  namespace: {{ .Values.namespace | default "default" }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
    {{- if and  (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type | default "ClusterIP" }}

